### ISSUE TITLE
返回数据格式异常

### ISSUE THREAD

**Issue by sunl888** [shima-park/agollo#13]
我apollo的数据是这样的：
```
appsalt = some appsalt

database.driver = mysql
database.host = mysql
database.port = 3306
database.user = root
database.password = 123456
database.dbname = chat
```
然后我的 struct 是这样定义的
```
type Config struct {
	AppSalt      string           `json:"appsalt"`
	DB           DatabaseConfig   `json:"database"`
        ...
}
type DatabaseConfig struct {
	Driver   string `json:"driver"`
	Host     string `json:"host"`
	Port     string `json:"port"`
	User     string `json:"user"`
	Password string `json:"password"`
	DBName   string `json:"dbname"`
}
```
apollo获取到的数据是这样的
```
map[appsalt:testaaaaa database.dbname:chat database.driver:mysql database.host:mysql database.password:123456 database.port:3306 database.user:root]
```
我怎么才能把获取到的这种数据映射到我的 struct中去呢？

**Comment by shima-park** [comment]
呃,这个好像不是我库的问题吧-_-! ...

不过，你可以这样解决你的问题。 兄dei记得star...
```
import (
        "fmt"
	"github.com/shima-park/agollo/viper-remote"
	"github.com/spf13/viper"
)

type Config struct {
	AppSalt string         `mapstructure:"appsalt"`
	DB      DatabaseConfig `mapstructure:"database"`
}
type DatabaseConfig struct {
	Driver   string `mapstructure:"driver"`
	Host     string `mapstructure:"host"`
	Port     string `mapstructure:"port"`
	User     string `mapstructure:"user"`
	Password string `mapstructure:"password"`
	DBName   string `mapstructure:"dbname"`
}

func xxx(){
    remote.SetAppID("your_appid")
    v := viper.New()
    v.SetConfigType("prop")
    err = v.AddRemoteProvider("apollo", "your_apollo_endpoint", "your_apollo_namespace")
    ... error handle
    err = v.ReadRemoteConfig()
    ... error handle

    var dbConfig Config
    err = v.Unmarshal(&dbConfig)
    ... error handle
    
    fmt.Printf("%+v\n", dbConfig)
}
```

**Comment by sunl888** [comment]
> 呃,这个好像不是我库的问题吧-_-! ...
> 
> 不过，你可以这样解决你的问题。 兄dei记得star...
> 
> ```
> import (
>         "fmt"
> 	"github.com/shima-park/agollo/viper-remote"
> 	"github.com/spf13/viper"
> )
> 
> type Config struct {
> 	AppSalt string         `mapstructure:"appsalt"`
> 	DB      DatabaseConfig `mapstructure:"database"`
> }
> type DatabaseConfig struct {
> 	Driver   string `mapstructure:"driver"`
> 	Host     string `mapstructure:"host"`
> 	Port     string `mapstructure:"port"`
> 	User     string `mapstructure:"user"`
> 	Password string `mapstructure:"password"`
> 	DBName   string `mapstructure:"dbname"`
> }
> 
> func xxx(){
>     remote.SetAppID("your_appid")
>     v := viper.New()
>     v.SetConfigType("prop")
>     err = v.AddRemoteProvider("apollo", "your_apollo_endpoint", "your_apollo_namespace")
>     ... error handle
>     err = v.ReadRemoteConfig()
>     ... error handle
> 
>     var dbConfig Config
>     err = v.Unmarshal(&dbConfig)
>     ... error handle
>     
>     fmt.Printf("%+v\n", dbConfig)
> }
> ```

OK，谢谢啦
