### ISSUE TITLE
agollo如何与viper接合实现监听

### ISSUE THREAD

**Issue by tidapeng** [shima-park/agollo#16]
请问agollo如何与viper接合实现监听，我调用viper.WatchRemoteConfig方法后，发现从viper读出来的值一直没有变化，而根目录下的.agollo文件却实时更新了。

**Comment by shima-park** [comment]
给我看看你是怎么写的

**Comment by shima-park** [comment]
```

**Comment by shima-park** [comment]
viper每次调用viper.WatchRemoteConfig后去对应的实现获取一次配置到kvstore.
要更新viper中的配置，需要自己起一个异步goroutine，定时去同步。
```
// Retrieve the first found remote configuration.
func (v *Viper) watchKeyValueConfig() error {
	for _, rp := range v.remoteProviders {
		val, err := v.watchRemoteConfig(rp)
		if err != nil {
			continue
		}
		v.kvstore = val
		return nil
	}
	return RemoteConfigError("No Files Found")
}

func (v *Viper) watchRemoteConfig(provider RemoteProvider) (map[string]interface{}, error) {
	reader, err := RemoteConfig.Watch(provider)
	if err != nil {
		return nil, err
	}
	err = v.unmarshalReader(reader, v.kvstore)
	return v.kvstore, err
}
```

**Comment by tidapeng** [comment]
>

> viper每次调用viper.WatchRemoteConfig后去对应的实现获取一次配置到kvstore.
> 要更新viper中的配置，需要自己起一个异步goroutine，定时去同步。
> 
> ```
> // Retrieve the first found remote configuration.
> func (v *Viper) watchKeyValueConfig() error {
> 	for _, rp := range v.remoteProviders {
> 		val, err := v.watchRemoteConfig(rp)
> 		if err != nil {
> 			continue
> 		}
> 		v.kvstore = val
> 		return nil
> 	}
> 	return RemoteConfigError("No Files Found")
> }
> 
> func (v *Viper) watchRemoteConfig(provider RemoteProvider) (map[string]interface{}, error) {
> 	reader, err := RemoteConfig.Watch(provider)
> 	if err != nil {
> 		return nil, err
> 	}
> 	err = v.unmarshalReader(reader, v.kvstore)
> 	return v.kvstore, err
> }
> ```

是的，viper确实没有实现对远程配置的监听与通知，只不过我看到在通过viper接入apollo时，虽然viper没有实时更新，但agollo却已经实时拉到了最新的配置(我查看.agollo缓存文件时发现已经是最新的了)，我想问这种情况下agollo有没有提供可用的通知机制，这样我可以监听agollo的更新通知然后再手动触发viper.WatchRemoteConfig去读取最新的配置？

**Comment by shima-park** [comment]
目前如果是完全基于viper暴露的api，是没办法获得事件通知，做相关处理的。
agollo这边因为获取第一次后Start()了一个goroutine去监听，哪里确实是获取到实时数据了。
但是由于这其实是两个库，之间一些处理是没法联动的。
比如我在一些viper示例中强调的要给viper设置configtype，虽然在agollo这边可以根据namespace的名字，知道文件类型进行序列化，反序列化。

针对你提的这个问题，和上面我说的这个问题，我在我们项目内部是封装了一个config库，提供了基于viper的配置获取api，以及{consul, etcd, apollo}的远程配置修改事件通知接口。

目前agollo库没有提供这样的功能，引入和实现viper接口，我最开始想的是利用viper本地，远程配置的封装，顺滑切换多个数据源，还有弥补单纯使用agollo库读取配置不方便的问题，如int，float，duration之类的配置项读取等等。

**Comment by tidapeng** [comment]
现在有两个问题，1.viper没法实时更新，即使调用了viper.WatchRemoteConfigOnChannel。2.viper没法将更新通知到业务。
针对第2个问题上面已经讨论了。
针对第1个问题：
viper第一次通过apolloConfigManager.Get方法获取配置内容，之后通过apolloConfigManager.watch返回的chan监听配置内容变更，我通过调试发现viper确实接收到变更事件，但获取到的内容和第一次的内容格式不匹配,多了一层{“content”:""}。查看agollo源码发现apolloConfigManager.Get方法会对内容作初步解析content := configs["content"].(string)，但apolloConfigManager.watch返回的内容没有作这层解析。
希望作者关注下。
agollo版本v.1.0.1

**Comment by shima-park** [comment]
确实有这个问题，你这里是使用了properties意外的配置文件格式把。
我想起来当初好像只测试了properties格式的情况。

**Comment by tidapeng** [comment]
> 确实有这个问题，你这里是使用了properties意外的配置文件格式把。
> 我想起来当初好像只测试了properties格式的情况。

是的，我用的yaml格式

**Comment by shima-park** [comment]
已经修复好了，这个问题在1.0.3版本中得到了修复。
谢谢你的反馈，如果有帮助到你，请帮忙star

**Comment by tidapeng** [comment]
> 已经修复好了，这个问题在1.0.3版本中得到了修复。
> 谢谢你的反馈，如果有帮助到你，请帮忙star

感谢

**Comment by tidapeng** [comment]
关于第二个问题2.viper没法将更新通知到业务，我最终采取的解决办法：
将viper封装的WatchRemoteConfigOnChannel逻辑自己在业务侧重新实现一遍。关键代码如下，提供给遇到这个问题的人一个参考：`
`
// viperRemoteProvider实现RemoteProvider接口
remoteProvider := viperRemoteProvider{
		provider:"apollo",
		endpoint:fmt.Sprintf("%s:%s",remoteConfig.Host,remoteConfig.Port),
		path:namespace,
	}
	viper.AddRemoteProvider(remoteProvider.provider,remoteProvider.endpoint,remoteProvider.path)

	err = viper.ReadRemoteConfig()
	if err != nil {
		// 无法读取远程配置信息
		retErr = fmt.Errorf("read remote config %s failed:%s",namespace,err.Error())
		return
	}
	resp,_ :=viper.RemoteConfig.WatchChannel(remoteProvider)

	go func(rr <-chan *viper.RemoteResponse){
		for {
			select{
			case <-rr:
				viper.ReadRemoteConfig()
				//handler()
			}
		}
	}(resp)
`

**Comment by shima-park** [comment]
谢谢tidapeng提供的解决方案。实际使用中如果有并发访问场景，还需要考虑一下viper库是线程不安全的。

**Comment by eyotang** [comment]
这个方案确实可以，解决了问题。

`type defaultRemoteProvider struct {
	provider      string
	endpoint      string
	path          string
	secretKeyring string
}

func (rp defaultRemoteProvider) Provider() string {
	return rp.provider
}

func (rp defaultRemoteProvider) Endpoint() string {
	return rp.endpoint
}

func (rp defaultRemoteProvider) Path() string {
	return rp.path
}

func (rp defaultRemoteProvider) SecretKeyring() string {
	return rp.secretKeyring
}
...
func WatchRemoteConfigOnChannel(v *viper.Viper, rp viper.RemoteProvider, onConfigChange func(*viper.Viper)) error {
	respCh, _ := viper.RemoteConfig.WatchChannel(rp)
	go func(rc <-chan *viper.RemoteResponse) {
		for {
			select {
			case <-rc:
				if err := v.ReadRemoteConfig(); err != nil {
					return
				}
				onConfigChange(v)
			}
		}
	}(respCh)
	return nil
}
...
业务代码：
rp := defaultRemoteProvider{
		provider: "apollo",
		endpoint: endPoint,
		path:     namespace,
	}
...
onConfigChange := func(v *viper.Viper) {
		fmt.Println("config file changed!")
		if err := v.Unmarshal(&global.GVA_CONFIG); err != nil {
			fmt.Println(err)
		}
	}
	if err = WatchRemoteConfigOnChannel(v, rp, onConfigChange); err != nil {
		fmt.Printf("监听配置变更失败，错误: %+v\n", err)
		return
	}
`
