### ISSUE TITLE
在remote中添加option的cluster参数不生效

### ISSUE THREAD

**Issue by DandelionJR** [shima-park/agollo#21]
我用viper来远程获取Apollo配置中心参数，使用了remote.SetAgolloOptions(agollo.Cluster("test"))添加了cluster信息，debug源码后发现请求的url地址都正确，但无法返回正确的配置信息，请问能给点建议吗

**Comment by DandelionJR** [comment]
经过多次测试发现。因为我设置了cluster，导致AutoFetchOnCacheMiss和FailTolerantOnBackupExists这两个默认参数消失，从而引起请求错误。请问为什么一定要加上这两个参数才能远程获取配置

**Comment by shima-park** [comment]
你这里是不是读取的默认的application以外的namespace无法获取配置

默认只初始化namespace: application,
结合viper使用时,默认情况下也不会预加载其他namespace
AutoFetchOnCacheMiss这个配置是自动加载,没有预加载时传入namespace的配置

FailTolerantOnBackupExists这个配置按需添加, 会在目录下生成容灾的备份文件
apollo配置服务连不上时,会读取其中的容灾配置.
