### ISSUE TITLE
提一些问题和建议

### ISSUE THREAD

**Issue by mofadeyunduo** [shima-park/agollo#22]
首先我个人想表扬作者，这个 agollo 实现不知道比官方推荐前两个实现好多少倍。前两个实现在我看来实在是太烂，过度的设计导致可读性和实用性变得极差。作者写简单和直接，也是 golang 官方倡导的。
其次我想提一些问题和建议：
1. Start 和 Stop 方法可以用 Context 的形式来做，就像 etcd 一样，这种模式是一种比较通用的模式，理解成本低
2. Watch 机制说实话我有点晕，我到现在也没跑通。我第一次启动 Watch 了配置竟然没有获取到配置，可否详细阐述下各种情况下 Watch 是怎么生效的？（可能和最近一次的提交有关）

**Comment by shima-park** [comment]
不好意思,我刚刚才看到你提的issue.谢谢你的赞赏.
官方那个页面的类库排序是根据贡献的时间先后排序的.
哈哈,我也是感觉太难用了所以写了这个库.但不可否认也是因为有前人开路才有了后来者.

1. 这里Start 和 Stop 方法 我为什么没有用 Context 的形式来做.
(1)使用channel或者Context去处理关闭其实都可以,当然现在现在新的库都会增加Context支持
(2)在写这个库的时候正好在看influxdb, filebeat这些库,他们在编写的时候context还没有普及,所以借鉴了他们的一些实现.

2. Watch 机制的一些问题
(1)Watch这块可能封装的不太好, 理解成本比较高,单纯Watch是没有效果的,
Watch和WatchNamespace仅仅是返回监听结果的channel.
(2)并且Readme刚刚我看了下漏了点示例.刚刚补了下

3. Watch没有获取到配置的原因,可能是如下几点
(1)监听配置需要Start后再进行Watch或者WatchNamespace, 没有跑通可能是没有Start
(2)apollo配置修改后没有提交修改

4.Watch 是怎么生效的
1. New方法创建 Agollo的实例时,预加载的namespace循环调用initNamespace
    initNamespace方法 通过apollo非缓存的配置接口拉取配置, 并将NotificationID设置为默认值 -1
3. Start方法 启动一个按照LongPollerInterval间隔轮训获取配置的goroutine.
 (1)调用apollo的Notifications接口获取需要更新的namespace和对应的NotificationID
 (2)isSendChange方法判断类库内部存储的namespace对应的NotificationID 是否大于 -1 
         [是]通过Watch/WatchNamespace的channel将改变结果返回
         [否]第一次初始化NotificationID,不发送通知

**Comment by mofadeyunduo** [comment]
感谢回复。
我还想请问下作者在公司里如何在生产环境下部署 apollo，目前我司这样部署的：
- 在两台机器 A、B 上分别部署 configservice、adminservice
- 在机器 A 上部署 portal
客户端访问是如何访问呢？我有几种想法：
- 走 Nginx 转发到 A、B，但是 Nginx 高可用在阿里云下很难实现（虚 IP）
- 走域名，这样很难限制 IP 访问
- 像 etcd 那样进行对多个 IP 进行轮询
不知楼主有没有什么建议或想法？

**Comment by mofadeyunduo** [comment]
感谢回复。
我还想请问下作者在公司里如何在生产环境下部署 apollo，目前我司这样部署的：
- 在两台机器 A、B 上分别部署 configservice、adminservice
- 在机器 A 上部署 portal
客户端访问是如何访问呢？我有几种想法：
- 走 Nginx 转发到 A、B，但是 Nginx 高可用在阿里云下很难实现（虚 IP）
- 走域名，这样很难限制 IP 访问
- 像 etcd 那样进行对多个 IP 进行轮询
不知楼主有没有什么建议或想法？

**Comment by shima-park** [comment]
Config Service、Eureka和Meta Server 在一个jvm中，configserver需要使用statefulset部署

dev、fat（qa）、pss、uat（pre）、pro（prd）环境单独数据库，隔离互不影响

部署在一个k8s 阿里云线上环境，因此prd和pre环境APOLLO_META（configmap）为k8s service地址，其余环境通过slb→ ingress 访问，DEV：apollo-dev.xxx.com, QA: apollo-fat.xxx.com 可公司直接访问

**Comment by mofadeyunduo** [comment]
感谢作者，先关闭了
