### ISSUE TITLE
不能监听所有 namespace 配置的变更

### ISSUE THREAD

**Issue by debuger6** [shima-park/agollo#23]
按照样例，不能监听所有 namespace 配置变更，从代码上看，创建客户端时，如果未填写 namespace 将会使用默认的 namespace，因此只能监听默认 namespace 的变更，这块能修复下吗？

**Comment by shima-park** [comment]
说明：
这些namespace只能由用户配置传入sdk，我这里并不能知道你有哪些namespace。

建议：
获取namespace列表涉及到另外一个需要鉴权的接口。
如果你不想写死，但想配置需要监听的namespace，我建议你结合另外一个sdk使用。

通过sdk: apollo-openapi的GetNamespaces方法获取当前env, appID, clusterName下的所有namespace。
然后通过sdk: agollo去监听配置。

参考：
[官方文档](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0#322--%E8%8E%B7%E5%8F%96%E9%9B%86%E7%BE%A4%E4%B8%8B%E6%89%80%E6%9C%89namespace%E4%BF%A1%E6%81%AF%E6%8E%A5%E5%8F%A3)

[apollo-openapi的获取所有namespace的sdk示例](https://github.com/shima-park/apollo-openapi/blob/master/client_test.go#L22)
