### ISSUE TITLE
namespace 首次创建，客户端监听不到

### ISSUE THREAD

**Issue by debuger6** [shima-park/agollo#24]
客户端启动监听某个namespace（尚未创建），当 namespace 创建时，客户端并未监听到，只能在 namespace 创建好后，更新配置才能被监听。望修复，谢谢。

**Comment by shima-park** [comment]
这个bug在最新的v1.1.1中已修复，如果有帮到你，可以star吗。

**Comment by debuger6** [comment]
> 这个bug在最新的v1.1.1中已修复，如果有帮到你，可以star吗。

已star

**Comment by shima-park** [comment]
谢谢
