### ISSUE TITLE
客户端负载均衡

### ISSUE THREAD

**Issue by HugeSkull** [shima-park/agollo#25]
点赞作者，简单的核心API留足了扩展能力，很棒的一个库~

Apollo架构上将Config、Meta、Eureka打在同一进程来做服务发现，咱们是否考虑利用MetaServer做客户端负载均衡，进一步提高可用性(对齐Java客户端)

**Comment by shima-park** [comment]
谢谢你的点赞和建议，这块不是你说我还真没注意到，刚刚去官方文档和代码中确实看到了这块内容，我近期完善一下。

**Comment by HugeSkull** [comment]
> 谢谢你的点赞和建议，这块不是你说我还真没注意到，刚刚去官方文档和代码中确实看到了这块内容，我近期完善一下。

期待~

**Comment by shima-park** [comment]
hi HugeSkull, 我在最新的v1.1.5中新增了客户端slb的实现。文档中增加了使用简介
https://github.com/shima-park/agollo#%E5%AE%A2%E6%88%B7%E7%AB%AFslb

**Comment by HugeSkull** [comment]
点赞作者的效率，我们即刻用起来~
