### ISSUE TITLE
关于配置自动更新的问题

### ISSUE THREAD

**Issue by Ami-Kawashima** [shima-park/agollo#27]
你好。我在代码中测试apollo的设置的时候，我使用了这里例子里的自动更新。但两种模式中，自动更新的方法，打印的结果始终是服务启动时候的内容，不会随着我在apollo界面的更改而更改。而10秒轮询的方法，可以成功访问到改了的和增加的数据，但是如果我删除了某个字段，在代码中仍然会打印该字段原先的值。
请问是需要什么额外的配置么？

**Comment by shima-park** [comment]
你好，我觉得可以从两个方面检查一下
（1）通过Watch方法来获取Namespace监听变更时，确认是否使用过PreloadNamespaces初始化过。
（2）本地是否开启翻墙的vpn代理导致获取配置失败。
