### ISSUE TITLE
[BUG] longpolling无限循环

### ISSUE THREAD

**Issue by fuermolv** [shima-park/agollo#30]
新建client时假如option中没有默认填入namespace application会自动添加到local storage中
```
	if len(options.PreloadNamespaces) == 0 {
		options.PreloadNamespaces = []string{defaultNamespace}
	} else {
		if !stringInSlice(defaultNamespace, options.PreloadNamespaces) {
			PreloadNamespaces(defaultNamespace)(&options)
		}
	}
```
如果使用longpolling接口，并且所监听的app-cluster中没有发布过"application" namespace会导致客户端按照默认的每秒访问一次 longpolling的几个相关接口

**Comment by shima-park** [comment]
谢谢你的反馈，确实对没有必要使用application的使用者造成了困扰。
我在 [fix version](https://github.com/shima-park/agollo/releases/tag/v1.1.11) 该版本删除了这段逻辑来修复此问题.
