### ISSUE TITLE
 accidentally panic

### ISSUE THREAD

**Issue by yorha59** [shima-park/agollo#31]
Hi, I'm using viper-remote and it will occasionally panic and stack print as bellow.
![image](https://user-images.githubusercontent.com/24535089/77310973-356ba800-6d3a-11ea-92b6-539a070f9ff1.png)

And I go on the code. I think type assertions may fix this panic.

**Comment by shima-park** [comment]
Thanks for you feedback.

1. Can you tell me which version you are using? if you using old version please try upgrade to latest version make sure that bug happens in the current version. I think this panic has been resolved on the latest version. [Pull Request](https://github.com/shima-park/agollo/pull/26)

2. If this panic occur again. Can you give me some extra information for debug. Such as configuration file format, some sample data
