### ISSUE TITLE
ticker 取数据，仅第一次能取到值

### ISSUE THREAD

**Issue by hea** [shima-park/agollo#34]
`

func main() {
	ch := make(chan string)
	a, err := agollo.New("localhost:8080",
		"hdy", agollo.Cluster("hdy-cluster"),
		agollo.DefaultNamespace("hdy.dev"),
		agollo.AutoFetchOnCacheMiss())
	if err != nil {
		panic(err)
	}
	a.Start()
	d := time.Duration(time.Second * 2)
	t := time.NewTicker(d)
	defer t.Stop()
	go func() {
		for {
			<-t.C
			fmt.Println(
				"user_max_count",a.Get("user_max_count",agollo.WithDefault("defaultValue")),
			)
		}
	}()
	ch <- ""
}

`

输出

user_max_count 3000000

user_max_count defaultValue

在不改配置的情况的，第一次能取到值，后面都是defaultValue
在Apollo页面改一次user_max_count的值，就能再取到数据不再是defaultValue

go的初学者，也是第一次用Apollo，请问这个事如何解决？

**Comment by shima-park** [comment]
你要实现的需求是啥，是要启动时读取一下配置，还是要一直监听配置修改。

**Comment by hea** [comment]
需要一直监听配置修改

**Comment by shima-park** [comment]
参考README中的示例代码，任何修改的配置项都会从watchCh中返回
```
a, err := agollo.New("localhost:8080", "your_appid", agollo.AutoFetchOnCacheMiss())
// error handle...

errorCh := a.Start()  // Start后会启动goroutine监听变化，并更新agollo对象内的配置cache
// 或者忽略错误处理直接 a.Start()

watchCh := a.Watch()

for{
	select{
	case err := <- errorCh:
		// handle error
	case resp := <-watchCh:
			fmt.Println(
			    "Namesapce:", resp.Namesapce,
			    "OldValue:", resp.OldValue,
			    "NewValue:", resp.NewValue,
			    "Error:", resp.Error,
			)
	}
}
```

**Comment by hea** [comment]
谢谢
