### ISSUE TITLE
如何获取yaml文件的配置呢？

### ISSUE THREAD

**Issue by 1stmud** [shima-park/agollo#36]
hi， 您好，我在apollo后台配置yaml文件类型的配置， 在客户端 .SetConfigType("yaml")  读不到配置
是不是我写法不对？

**Comment by shima-park** [comment]
你使用那种方式呢，默认的获取配置方式，还是结合viper方式。
可以的话贴下你的示例代码。

默认的读取方式
```
a, err := agollo. New(configServerUrl, appId, agollo.AutoFetchOnCacheMiss())
// .. err handle
fmt.Println(a.GetNameSpace("your_config.yaml"))
```

结合viper的读取方式
https://github.com/shima-park/agollo#%E7%BB%93%E5%90%88viper%E4%BD%BF%E7%94%A8%E6%8F%90%E9%AB%98%E9%85%8D%E7%BD%AE%E8%AF%BB%E5%8F%96%E8%88%92%E9%80%82%E5%BA%A6

**Comment by 1stmud** [comment]
我用的viper方式， 找到不能获取配置文件的原因了， 我创建了一个私有类型是yaml格式的配置， namespace 取名test，  在 apollo后台看到namespace显示也是test ,  但实际上是test.yaml

 原addRemoteProvider的时候 path 是 test,  改成  test.yaml 好了。

```
yamltest.AddRemoteProvider("apollo","localhost:8080","test.yaml")
```
谢谢你大佬

**Comment by shima-park** [comment]
是的，这点没注意很坑，apollo只有默认的properties格式的不用加后缀
其他的配置文件格式都需要加后缀
