### ISSUE TITLE
viper方式多namespace支持问题

### ISSUE THREAD

**Issue by 1stmud** [shima-park/agollo#37]
目前是v.AddRemoteProvider("apollo", Endpoint, NameSpace)
namespace只支持传入一个， 如果同一个app下有多个yaml或者json的配置文件 ，是否可以一次性获取多个namespace下的配置？  

我看viper的AddRemoteProvider 是支持多次加入的， 放到了 v.remoteProviders   ，获取的时候ReadRemoteConfig 也是支持循环remoteProviders的

如果项目支持 namespace传入切片就很棒了

**Comment by shima-park** [comment]
这样处理的原因是不同namespace可能会有相同的key，
导致viper中存储k,v的map相互覆盖，导致配置不对
如果你有不同的namespace我建议是创建多个viper对象分别去加载和读取

**Comment by 1stmud** [comment]
嗯， 目前是的 直接new多个viper对象
相互覆盖是使用者的问题， 支持不支持是设计问题  ，viper设计支持多次AddRemoteProvider 就说明这个是合理的  ，我只是建议， 大佬可以考虑下  ，你的viper remote方式很棒

**Comment by shima-park** [comment]
viper支持多次AddRemoteProvider应该是为了容错之类的
他只会从remoteProviders这个列表中，获取没有出错的那次配置就return
而不会将所有providers配置加载进来，所以即使能传多个namespace也只有其中一个的配置
```
func (v *Viper) getKeyValueConfig() error {
	if RemoteConfig == nil {
		return RemoteConfigError("Enable the remote features by doing a blank import of the viper/remote package: '_ github.com/spf13/viper/remote'")
	}

	for _, rp := range v.remoteProviders {
		val, err := v.getRemoteConfig(rp)
		if err != nil {
			continue
		}
		v.kvstore = val
		return nil
	}
	return RemoteConfigError("No Files Found")
}
```
