### ISSUE TITLE
该 SDK 可以获取一个命名空间下的实例列表吗？

### ISSUE THREAD

**Issue by stone2014** [shima-park/agollo#38]
可以通过 SDK 获取 一个命名空间下的配置信息，如端口号等。可以获取对应的机器列表吗？

**Comment by shima-park** [comment]
获取不了，当前这个sdk是针对apollo配置读取的封装。
获取命名空间下的实例列表，我刚刚在apollo openapi下找了下也没看到
[apollo openapi文档](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

针对openapi的访问可以用我封装的这个库: [openapi](https://github.com/shima-park/apollo-openapi)

**Comment by stone2014** [comment]
好的，多谢您的及时帮助，多谢了。
