### ISSUE TITLE
可以让crypt支持apollo吗？

### ISSUE THREAD

**Issue by Icedroid** [shima-park/agollo#4]
https://github.com/xordataexchange/crypt/blob/master/backend/backend.go
实现这些接口就可以了吧，像etcd一样。

**Comment by shima-park** [comment]
是可以，但是需要你要自己去fork一下crypt去改造一下。crypt没有提供额外的实现类注册。https://github.com/xordataexchange/crypt/blob/master/bin/crypt/cmd.go
这个里面写死了只有consul，etcd两种

**Comment by Icedroid** [comment]
我试了一下，发现不能SET，应该不行，Apollo 没有提供设置值的接口。

**Comment by shima-park** [comment]
有提供，不过你要把好几个接口结合起来。
https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0

1）3.2.4 创建Namespace
可以通过此接口创建Namespace，调用此接口需要授予第三方APP，APP级别的权限。

URL ： http://{portal_address} /openapi/v1/apps/{appId}/appnamespaces

2）3.2.5 获取某个Namespace当前编辑人接口
Apollo在生产环境（PRO）有限制规则：每次发布只能有一个人编辑配置，且该次发布的人不能是该次发布的编辑人。 也就是说如果一个用户A修改了某个namespace的配置，那么在这个namespace发布前，只能由A修改，其它用户无法修改。同时，该用户A无法发布自己修改的配置，必须找另一个有发布权限的人操作。 这个接口就是用来获取当前namespace是否有人锁定的接口。在非生产环境（FAT、UAT），该接口始终返回没有人锁定。

URL ： http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/lock

3）3.2.7 修改配置接口
URL ： http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/{key}

4）3.2.8 删除配置接口
URL ： http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/{key}?operator={operator}

5）3.2.9 发布配置接口
URL ： http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/releases
