### ISSUE TITLE
程序启动时如无法连接上配置中心，则后续也无法刷新配置

### ISSUE THREAD

**Issue by logo306142054** [shima-park/agollo#40]
当程序启动时如无法连接上配置中心，则后续即使配置中心启动或恢复正常，程序也无法获取到配置。通过代码走读，发现问题是由于a.cache和a.initialized这两个map的LoadOrStore调用不太合理导致。我做了一点小改动以适应这种场景。请查阅一下我的修改是否有问题
https://github.com/logo306142054/agollo/commit/d48c7472d66a62e3af7e72067b1939905289865a?diff=split

**Comment by shima-park** [comment]
非常感谢你的反馈。

你这边是不是有启动时不关心服务是否可以连上，忽略错误启动，
这种情况我之前测试倒是没关注，因为我是出错就panic退出进程。。。
如果是的话，我看了下你这个修改可以应付这种场景。

主要就是初始化时，即使出现error，也要将notificationMap初始化，
使longPoll在轮训时有参数去请求apollo，在apollo恢复后拿到通知reloadNamespace

这个问题我在最新的release版本中也进行修复支持[release](https://github.com/shima-park/agollo/releases/tag/v1.2.5)

**Comment by logo306142054** [comment]
感谢采纳。
在我们的业务逻辑中，服务启动时读取配置是必须的，但panic退出并不是唯一的选择，可以考虑轮询等待，直到读取到配置后再继续完成初始化，此时可以增加日志打印以提示
