### ISSUE TITLE
数组问题

### ISSUE THREAD

**Issue by pengbinbin1** [shima-park/agollo#41]
如果配置文件中有数组形式，使用viper没有解析出来，请问这种情况该咋操作
![image](https://user-images.githubusercontent.com/28950491/85125613-84a07680-b25e-11ea-9110-19c2d81a9070.png)

**Comment by pengbinbin1** [comment]
打印的解析如下 ，不是数组的都解析到了
![image](https://user-images.githubusercontent.com/28950491/85125758-cb8e6c00-b25e-11ea-93fa-79b6b06918d3.png)

**Comment by shima-park** [comment]
你这个用的是properties格式的配置文件吧，properties本身只是key:value没有数组类型
数组这种定义属于自定义的去解析的.

**Comment by shima-park** [comment]
我之前去处理这个问题是再封装了一个读取配置的库。可以的话最好是换个配置文件格式。

```
var i int
var arr []string
for {
    key := fmt.Sprintf("case[%d]", i)
    if viper.IsSet(key) {
        value := viper.Get(key)
        arr = append(arr, value)
        i++
        continue
    }
    break
}
```
老铁，如果有帮到你记得star

**Comment by pengbinbin1** [comment]
apollo的web界面支持直接导入yaml格式的文件吗，本来是配置文件是yml格式的，导成了prop格式的贴到apollo里的

**Comment by pengbinbin1** [comment]
另外，使用viper的时候，有没有类似于注册一个回调，只要配置有更新就会调用我注册的回调的机制。看例程中有忙轮询和监听两种。监听的那种也是要死循环去不断重新获取的，有没有类似主动通知的那种。不管能不能帮上，start没毛病

**Comment by shima-park** [comment]
> apollo的web界面支持直接导入yaml格式的文件吗，本来是配置文件是yml格式的，导成了prop格式的贴到apollo里的

支持的只是apollo这个ui做的比较傻，藏的比较深
![image](https://user-images.githubusercontent.com/4186507/85189556-a80d0500-b2e2-11ea-9d99-d421be5e7b30.png)
![image](https://user-images.githubusercontent.com/4186507/85189564-bb1fd500-b2e2-11ea-8936-306792f22119.png)
namespace如果是public的在界面点public就好来，创建出来就是public的yml/yaml格式的

更便捷的方式你可以用我封装的apollo openapi的sdk去同步配置，而不是手动去copy啥的
之前我们的配置是存在consul后来迁移到了apollo，手动迁移一堆配置又累又不靠谱
https://github.com/shima-park/apollo-openapi

**Comment by shima-park** [comment]
> 另外，使用viper的时候，有没有类似于注册一个回调，只要配置有更新就会调用我注册的回调的机制。看例程中有忙轮询和监听两种。监听的那种也是要死循环去不断重新获取的，有没有类似主动通知的那种。不管能不能帮上，start没毛病

viper本身没有提供事件回调的方法，它属于一种比较上层的封装了，你如果要这个特性的话，可能要fork它做一些功能改造。增加注册Hook方法，在watchKeyValueConfigOnChannel加上调用Hook。

https://github.com/spf13/viper/blob/v1.7.0/viper.go#L1772
getKeyValueConfig读取一次远程配置更新本地维护的kvstore这个map

https://github.com/spf13/viper/blob/v1.7.0/viper.go#L1798
watchKeyValueConfigOnChannel 它这个内部开了goroutine消费更新事件，更新本地维护的kvstore，不再向外传递事件

**Comment by pengbinbin1** [comment]
感谢帮助
