### ISSUE TITLE
json 的namespace内容保存在content里面，且是一个带双引号 字符串格式

### ISSUE THREAD

**Issue by chowyu08** [shima-park/agollo#44]

**Comment by shima-park** [comment]
apollo响应的结构就是这样的。
properties的结果是key:value...
```
// 类似这样
{
  "appId": "100004458",
  "cluster": "default",
  "namespaceName": "application",
  "configurations": {
    "portal.elastic.document.type":"biz",
    "portal.elastic.cluster.name":"hermes-es-fws"
  },
  "releaseKey": "20170430092936-dee2d58e74515ff3"
}
```
非properties的结果是包在content里的{json, yaml, toml...}
```
{
  "appId": "100004458",
  "cluster": "default",
  "namespaceName": "test.yaml",
  "configurations": {
    "content" : "timeout=123"
  },
  "releaseKey": "20170430092936-dee2d58e74515ff3"
}
```

**Comment by chowyu08** [comment]
问题是通过map["content"]拿到的是是一个包含”“的字符串：
”{\"a\":1}“这种，导致json.Unmarshal错误：cannot unmarshal string into Go value of type map[string]interface {}

**Comment by shima-park** [comment]
... 是不是在配置的时候最外面包了个双引号

![image](https://user-images.githubusercontent.com/4186507/88641342-a0b2f580-d0f1-11ea-84e6-83e74a7cecf5.png)
![image](https://user-images.githubusercontent.com/4186507/88641357-a90b3080-d0f1-11ea-8e6a-52e1d685060c.png)
![image](https://user-images.githubusercontent.com/4186507/88641368-adcfe480-d0f1-11ea-9e47-e276bd8e98d7.png)
