### ISSUE TITLE
监听application.properties时watch到变化时获取的namespace是application而不是application.properties

### ISSUE THREAD

**Issue by wxning1107** [shima-park/agollo#45]
你好！监听application.properties时watch到变化时获取的namespace是application而不是application.properties，请问这个有什么办法让wathc拿到的namesapce和new时传入到namespace保持一致嘛，谢谢

**Comment by wxning1107** [comment]
传入application和application.properties效果是一样的，好吧，为什么application带不带后缀都行，而yaml或者json必须带后缀呢

**Comment by shima-park** [comment]
这个问题要问apollo的开发团队了

可能他们java技术栈properties配置文件格式用的比较多，其他配置文件格式应该是后来加的
而且从给的接口数据上来看，存储应该也是不一样的。
properties
```
{
"key": "value",
"key2":"value2"
...
}
```

json/yaml/xml ...
```
{
"content" : "json/yaml/xml data"
}
```

**Comment by wxning1107** [comment]
使用agollo.stop后goroutine没有减为0，发现还有3个goroutine存活

**Comment by shima-park** [comment]
👍阔以，这都被你发现了，我倒是没注意，刚刚提交了一个补丁，应该修正了stop后goroutine没退出的问题。

**Comment by wxning1107** [comment]
好的，已经解决了，需要sleep超过90秒才能完全释放goroutine，非常感谢。

**Comment by shima-park** [comment]
了解了，轮训哪里做的粗糙了点。longPull轮训的那个goroutine被apollo服务器hold了90秒，等待期间是否有修改返回。
这个http request我没有传入带关闭事件的Context，所以要等90秒后，轮训再次触发select最后一个goroutine才退出。
