### ISSUE TITLE
结合viper并通过ACCESSKEY_SECRET访问

### ISSUE THREAD

**Issue by lijiansgit** [shima-park/agollo#48]
看文档应该不支持吧？什么时候支持呢？

**Comment by shima-park** [comment]
通过配置项参数,设置好access_key就可以了
```
import (
    "github.com/shima-park/agollo"
    "github.com/shima-park/agollo/remote"
)

func main(){
    remote. SetAgolloOptions(
        agollo.WithClientOptions(agollo.WithAccessKey("your_access_key"))
    )
    remote.SetAppID("your_appid")

    v := viper.New()
    v.SetConfigType("prop")
    err := v.AddRemoteProvider("apollo", "your_apollo_endpoint", "your_apollo_namespace")
    // error handle...
    err = v.ReadRemoteConfig()
    // error handle...
}
```

**Comment by lijiansgit** [comment]
done! thanks

**Comment by lijiansgit** [comment]
测试一旦使用remote. SetAgolloOptions()之后，就获取不到值了，查看源码发现需要加上：
remote.SetAgolloOptions(agollo.AutoFetchOnCacheMiss(),......)
AutoFetchOnCacheMiss设计的目的是什么呢？那是不是需要在remote.SetAgolloOptions()函数里默认就加上呢

**Comment by shima-park** [comment]
好奇怪，我昨天回复提交了，没看到记录了.

AutoFetchOnCacheMiss 按需配置的，自动获取没有Preload的Namespace，
算是一个懒人配置，或者在需要加载的namespace比较多，手动指定又比较烦的情况

另一种是在初始化的时候，显示的通过PreloadNamesapce("ns1", "ns2") 加载

这两个配置项在初始化时，是需要二选一去配置的，否则无法加载配置。
