### ISSUE TITLE
请问非properties需要怎么处理

### ISSUE THREAD

**Issue by hardy1970** [shima-park/agollo#5]
json yml 格式的配置需要如何获取，用获取properties 方式返回404？

**Comment by shima-park** [comment]
比如你有一个叫test.json的namespace，其中存储的文本内容为{"key":"value"}。

方式1: 
```
    err := agollo.InitWithDefaultConfigFile(
          agollo.PreloadNamespaces("test.json"),
    )
    agollo.GetNameSpace("test.json")  // 返回 map[content:{"key":"value"}]  需要你自己取出反序列化
```
方式2:
```
    err := agollo.InitWithDefaultConfigFile(...)
    agollo.GetNameSpace("test.json") // 返回 map[content:{"key":"value"}]  需要你自己取出反序列化
```
// 区别在于未经过PreloadNamespaces会产生修改事件,Watch会收到该事件

apollo支持properties、xml、yml、yaml、json
它默认格式为properties且不带后缀的，如果是其它格式需在后面增加对应后缀 namespace.{文件格式}
如果你要获取yml的配置，对应在namespace后加对应后缀如: test.yml

文件格式为json时，apollo实际接口返回的内容如下:
```
{
	"appId": "Test",
	"cluster": "default",
	"namespaceName": "test.json",
	"configurations": {
		"content": "{\"test\":\"value\"}"
	},
	"releaseKey": "20190515174751-512ed4b31b5e5f4b"
}
```

文件格式为默认的properties时，apollo实际接口返回的内容如下：
```
{
	"appId": "Test",
	"cluster": "default",
	"namespaceName": "application",
	"configurations": {
		"key": "value1",
		"key2": "value2",
		...
	},
	"releaseKey": "20190515092306-69bad4b31b5e5f4a"
}
```

**Comment by hardy1970** [comment]
非properties类型的这种能用agollo.New 这种方式创建对象吗？像之前获取properties 是用这种方式
```
if appConfig.ConfigType == "properties" {
			newAgo, err := agollo.New(
				appConfig.ConfigServerUrl,
				appConfig.AppId,
				agollo.Cluster(cluster),
				agollo.PreloadNamespaces(appConfig.NamespaceName),
				agollo.AutoFetchOnCacheMiss(),
				agollo.FailTolerantOnBackupExists(),
				agollo.WithLogger(agollo.NewLogger(agollo.LoggerWriter(os.Stdout))),
			)

			if err != nil {
				panic(err)
			}

			res := newAgo.GetNameSpace(appConfig.NamespaceName)
			log.Println("----", reflect.TypeOf(res), res)
}
```

**Comment by shima-park** [comment]
当然可以的。

**Comment by hardy1970** [comment]
测试yml格式的namespace用这种方式获取，返回404. 为什么路径中会带有json呢
```
			newAgo, err := agollo.New(
				appConfig.ConfigServerUrl,
				appConfig.AppId,
				agollo.Cluster(cluster),
				agollo.PreloadNamespaces(appConfig.NamespaceName),
				agollo.AutoFetchOnCacheMiss(),
				agollo.FailTolerantOnBackupExists(),
				agollo.WithLogger(agollo.NewLogger(agollo.LoggerWriter(os.Stdout))),
			)

			if err != nil {
				panic(err)
			}

			res := newAgo.GetNameSpace(appConfig.NamespaceName)
                        log.Println("----", reflect.TypeOf(res), res)
```
```
res返回是空map ，---- agollo.Configurations map[]
[Agollo]  ConfigServerUrl xxx:8080 AppID zb-crm-tomcat Cluster application-dev.yml Namespace eq-220.241.124.247 Action LoadConfigFromCache Error {"timestamp":"2019-05-16T10:32:51.406+0800","status":404,"error":"Not Found","message":"Could not load configurations with appId: zb-crm-tomcat, clusterName: application-dev.yml, namespace: eq-220.241.124.247","path":"/configfiles/json/zb-crm-tomcat/application-dev.yml/eq-220.241.124.247"}
```

**Comment by hardy1970** [comment]
> 测试yml格式的namespace用这种方式获取，返回404. 为什么路径中会带有json呢
> 
> ```
> 			newAgo, err := agollo.New(
> 				appConfig.ConfigServerUrl,
> 				appConfig.AppId,
> 				agollo.Cluster(cluster),
> 				agollo.PreloadNamespaces(appConfig.NamespaceName),
> 				agollo.AutoFetchOnCacheMiss(),
> 				agollo.FailTolerantOnBackupExists(),
> 				agollo.WithLogger(agollo.NewLogger(agollo.LoggerWriter(os.Stdout))),
> 			)
> 
> 			if err != nil {
> 				panic(err)
> 			}
> 
> 			res := newAgo.GetNameSpace(appConfig.NamespaceName)
>                         log.Println("----", reflect.TypeOf(res), res)
> ```
> 
> ```
> res返回是空map ，---- agollo.Configurations map[]
> [Agollo]  ConfigServerUrl xxx:8080 AppID zb-crm-tomcat Cluster application-dev.yml Namespace eq-220.241.124.247 Action LoadConfigFromCache Error {"timestamp":"2019-05-16T10:32:51.406+0800","status":404,"error":"Not Found","message":"Could not load configurations with appId: zb-crm-tomcat, clusterName: application-dev.yml, namespace: eq-220.241.124.247","path":"/configfiles/json/zb-crm-tomcat/application-dev.yml/eq-220.241.124.247"}
> ```

这种方式获取properties 类型的是OK的，但是获取yml 类型的是返回404的。

**Comment by shima-park** [comment]
请求路径里带json是apollo接口就是如此。看下面链接有接口文档信息。

我看你的日志好像你的集群和namespace配置不对。
Cluster application-dev.yml 
Namespace eq-220.241.124.247
Namespace应该是eq-220.241.124.247.yml吧
你可以自己curl或者浏览器访问一下：
http://{your_ ConfigServerUrl}/configfiles/json/zb-crm-tomcat/application-dev/eq-220.241.124.247.yml

https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#12-%E9%80%9A%E8%BF%87%E5%B8%A6%E7%BC%93%E5%AD%98%E7%9A%84http%E6%8E%A5%E5%8F%A3%E4%BB%8Eapollo%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE

**Comment by hardy1970** [comment]
有一点比较奇怪的是，日志中报的是下面找不到 404
/configfiles/json/zb-crm-tomcat/application-dev.yml/eq-220.241.124.247
但是我手动在namespace 后面添加一个yml 就可以。应该是我Namespace配置有问题。因为之前是properties 的Namespace 也没有带后缀 直接这样eq-220.241.124.247 看没报错所以没关注。
/configfiles/json/zb-crm-tomcat/application-dev.yml/eq-220.241.124.247.yml
感谢感谢！！！！
(非properties类型的namespace请加上类型后缀，例如apollo.xml) 没有注意这个点。
![image](https://user-images.githubusercontent.com/44759712/57823554-8fbae480-77ca-11e9-9148-0cc25fd8be7a.png)
