### ISSUE TITLE
start、watch 无法监听配置

### ISSUE THREAD

**Issue by MisterChing** [shima-park/agollo#53]
agolloClient, err := agollo.New(
		"xx",
		"xx",
		agollo.BackupFile(backupFile),
		agollo.AutoFetchOnCacheMiss(),
		agollo.PreloadNamespaces("xx.json"),
	)
	errChan := agolloClient.Start()
	watchChan := agolloClient.Watch()
	ticker := time.NewTicker(1 * time.Second)
	for {
		select {
		case <-ticker.C:
			ret := agolloClient.GetNameSpace("xx.json")
 			base.Test_debug(ret, 0)
		case err := <-errChan:
			base.Test_debug(err, 0)
		case resp := <-watchChan:
			base.Test_debug(resp, 0)
		}

为什么只在启动时打印出了一次xx.json的值，后续打印都是空。任何修改变动，都没有任何打印。

**Comment by shima-park** [comment]
修改apollo的配置后，有没有发布配置

**Comment by MisterChing** [comment]
> 修改apollo的配置后，有没有发布配置

有发布。不修改apollo配置。在select中也只能打印出最初的一次值

**Comment by shima-park** [comment]
可以加入日志的参数选项，开启日志，看看具体出现了什么异常。
```
agolloClient, err := agollo.New(
        "localhost:8080",
        "SampleApp",
        agollo.WithLogger(agollo.NewLogger(agollo.LoggerWriter(os.Stdout))),
        agollo.AutoFetchOnCacheMiss(),
        agollo.PreloadNamespaces("application", "TEST1.json"),
    )
```

我用上面你给的代码，测试过了是可以的。你再检查下namspace的名字是否正确。
```
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/shima-park/agollo"
)

func main() {
	agolloClient, err := agollo.New(
		"localhost:8080",
		"SampleApp",
		agollo.WithLogger(agollo.NewLogger(agollo.LoggerWriter(os.Stdout))),
		agollo.AutoFetchOnCacheMiss(),
		agollo.PreloadNamespaces("test.json", "TEST1.json.json"),
	)
	if err != nil {
		panic(err)
	}

	fmt.Println(agolloClient.GetNameSpace("TEST1.json.json"), agolloClient.GetNameSpace("test.json"))
	errChan := agolloClient.Start()
	watchChan := agolloClient.Watch()
	ticker := time.NewTicker(5 * time.Second)
	for {
		select {
		case <-ticker.C:
			fmt.Println("Ticker:",
				"TEST1.json.json", agolloClient.GetNameSpace("TEST1.json.json"), "\n",
				"test.json", agolloClient.GetNameSpace("test.json"),
			)
		case err := <-errChan:
			fmt.Println(err, 0)
		case resp := <-watchChan:
			fmt.Println("Notify:", resp, 0)
		}
	}
}
```
![image](https://user-images.githubusercontent.com/4186507/99036779-41ec8b80-25bd-11eb-8187-48b1c7240899.png)


我在测试的时候就碰到一个坑
![image](https://user-images.githubusercontent.com/4186507/99036133-1026f500-25bc-11eb-8324-7e6c7ace6dc2.png)

图中第二个namespace: TEST1.json 实际namespace是 TEST1.json.json
后面两个namespace: test.json, test.yaml

**Comment by MisterChing** [comment]
我尝试加了日志，还是不正常。能监听到了，但值没有被修改

![Xnip2020-11-13_17-56-57](https://user-images.githubusercontent.com/7869492/99059963-45424000-25da-11eb-9dda-b75211699bc5.jpg)

**Comment by shima-park** [comment]
![Screenshot_20201113_184300](https://user-images.githubusercontent.com/4186507/99063832-162ecd00-25e0-11eb-9b8d-3db27b590f52.jpg)

你就用我上一个回复贴的示例代码，改成你的配置试试看。
还有库的tag你看是不是最新的版本v1.2.7
