### ISSUE TITLE
我不想要备份文件, 可以去掉么, 它无论如何都会创建一个备份文件我关不掉

### ISSUE THREAD

**Issue by zlyuancn** [shima-park/agollo#57]
# 希望加个选项控制是否写入到备份文件, 或者备份文件名为空字符串就不备份

**Comment by zlyuancn** [comment]
# 或者提供一个选项由用户传入io.Writer

**Comment by shima-park** [comment]
我搜了下，看这里说[blog](https://bbs.huaweicloud.com/blogs/146535)
windows有个`nul`相当于linux下的`/dev/null`

**Comment by zlyuancn** [comment]
我去我从来不知道win下面居然有这个, 试了一下果然丢弃了. 不过, 要是能拦截下backup由用户自由储存就好了, 这个需求只是个建议, 我没考虑实用性.

**Comment by shima-park** [comment]
是的, 可以配置备份的io.Writer会更好
这块改动比较多，因为不止有备份写入，还有备份读取
实际需要提供一个ReadWriter配置项

**Comment by zlyuancn** [comment]
是的, 这个优先级不高, 目前想不出什么使用场景, 因为我从不可能把备份存redis或别的第三方服务, 这本末倒置了.

但是我如果想关闭备份就要对win和linux提供不同的参数, 我是用win开发然后部署在linux

**Comment by zlyuancn** [comment]
我目前是这样解决的

```go
if conf.BackupFile != "" {
    opts = append(opts, agollo.BackupFile(conf.BackupFile))
}else if runtime.GOOS == "windows"{
    opts = append(opts, agollo.BackupFile("/nul"))
}else{
    opts = append(opts, agollo.BackupFile("/dev/null"))
}
```
