### ISSUE TITLE
can't get value by Env？

### ISSUE THREAD

**Issue by chenxinya** [shima-park/agollo#61]
hello，问一下原生apollo 不是 value 级别应该是，应用-->环境--> 集群-->namespace吗？我看到里面没有实现根据环境进行得到相应的配置，请问是为什么？

**Comment by shima-park** [comment]
你是说根据dev, fat, prd不同的开发环境读取配置？

apollo的不同的config server对应的是一个不同的服务地址
{dev_config_server_address}/configs/{appid}/{cluster}/{namespace}
{fat_config_server_address}/configs/{appid}/{cluster}/{namespace}
...

用sdk的时候，你只需把当前环境的config server address传入，
如果你需要读取不同环境的配置，那就需要通过不同的地址，创建多个不同的sdk的实例

**Comment by chenxinya** [comment]
嗯，谢谢，我先看一下
