### ISSUE TITLE
apollo中使用yaml格式的配置文件，viper读取为空

### ISSUE THREAD

**Issue by AkatsukiAkira** [shima-park/agollo#66]
![image](https://user-images.githubusercontent.com/29282808/129587031-57a8685a-0efd-46a4-b1ff-8abb2bfb0ab7.png)
![image](https://user-images.githubusercontent.com/29282808/129587099-31cf61fc-8c4f-4054-b9da-d98a599b73f9.png)
如图，读取配置时为空

**Comment by shima-park** [comment]
![image](https://user-images.githubusercontent.com/4186507/129650542-bdd5b5f2-3f7c-4209-b3ad-06d9bec563b1.png)

**Comment by AkatsukiAkira** [comment]
嗯嗯，可以了。谢谢
很好用

**Comment by shima-park** [comment]
谢谢😄
