### ISSUE TITLE
如何获取application下所有的key？

### ISSUE THREAD

**Issue by yibin001** [shima-park/agollo#68]
发新没有方法可以获取application的所有key列表

**Comment by shima-park** [comment]
有的 GetNameSpace("application")，会返回这个namespace下的所有key, value
```
GetNameSpace(namespace string) Configurations

type Configurations map[string]interface{}
```

**Comment by yibin001** [comment]
谢谢回复，不知道这个sdk能否做到跟java的一样，本地有自己的配置文件，sdk优先从远程读取配置并覆盖本地配置，如果远程没有，则用本地配置。

**Comment by shima-park** [comment]
功能有的，可以看下项目首页下的ReadMe，有一些常用的功能介绍
https://github.com/shima-park/agollo#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%97%B6%E5%8F%AF%E9%80%89%E9%85%8D%E7%BD%AE%E9%A1%B9

创建sdk实例的时候传入这个可选配置项，会在无法读取到远程服务器时，尝试在本地在容灾配置文件。
```
// 在连接apollo失败时，如果在配置的目录下存在.agollo备份配置，会读取备份在服务器无法连接的情况下
agollo.FailTolerantOnBackupExists(),
```
