### ISSUE TITLE
与viper 一起用时候怎么切换或者说选择apollo的cluster呢

### ISSUE THREAD

**Issue by yigerenluxing** [shima-park/agollo#69]

**Comment by shima-park** [comment]
remote.go里有一个全局方法SetAgolloOptions里面可以传Cluster("your_cluster")

**Comment by yigerenluxing** [comment]
![image](https://user-images.githubusercontent.com/29767431/146110569-e84e98b3-c515-4675-9827-24d05d7a712d.png)
这样设置apollo的 Cluster 没有作用，default集群应该是有数据的，如果不使用remote.SetAgolloOptions(options)方法就可以获取到集群这是为什么呢

**Comment by yigerenluxing** [comment]
![image](https://user-images.githubusercontent.com/29767431/146110886-3388730f-3d07-45e1-8196-16674cb7e941.png)
      请问下SetAgolloOptions设置了cluster 看起来好像没有起作用，设置default 反而拿不到值，不设置就获取到了，请问SetAgolloOptions如果不传参是默认default吗

**Comment by shima-park** [comment]
默认是default。
SetAgolloOptions时，有个要注意的地方忘记说了，因为这个方法会覆盖默认的配置项
默认我是设置了下面两个配置项
```
defaultAgolloOptions = []agollo.Option{
		agollo.AutoFetchOnCacheMiss(),  // namespace不存在或者未初始化时，从apollo接口拉取配置
		agollo.FailTolerantOnBackupExists(), // 容灾在apollo连接不上时
	}
```

单独设置，remote.SetAgolloOptions(agollo.Cluster("default"))，会把上面两个配置覆盖。

简而言之，拿不到值，是因为AutoFetchOnCacheMiss被覆盖了
```
remote.SetAgolloOptions(
    agollo.Cluster("default"),
    agollo.AutoFetchOnCacheMiss(),  // namespace不存在或者未初始化时，从apollo接口拉取配置
    agollo.FailTolerantOnBackupExists(), // 容灾在apollo连接不上时
)
```

**Comment by yigerenluxing** [comment]
谢谢，设置后可以取到了
