### ISSUE TITLE
apollo的meta地址必须非http得BUG

### ISSUE THREAD

**Issue by storv** [shima-park/agollo#7]
`url := fmt.Sprintf("http://%s/configs/%s/%s/%s?releaseKey=%s&ip=%s",
		configServerURL,
		url.QueryEscape(appID),
		url.QueryEscape(cluster),
		url.QueryEscape(c.getNamespace(namespace)),
		options.ReleaseKey,
		c.IP,
	)`
这里不需要直接制定一个`http`

**Comment by storv** [comment]
我的环境的地址为https://apollo.xxx.xxx:xxxx

**Comment by storv** [comment]
#9

**Comment by shima-park** [comment]
谢谢你的反馈，看到了你的pr，这样改还是有点问题，像我们公司发布系统配置的地址没带协议类型：http://和https://
传递的话使用传递的协议类型，或者不传默认使用http://，我加下这个逻辑。

**Comment by storv** [comment]
好的 开始认为默认会自动加一个http。刚刚测试了一下 发现没有。比较意外
