### ISSUE TITLE
使用viper时,是否能暴露一个配置变更的方法

### ISSUE THREAD

**Issue by 63isOK** [shima-park/agollo#74]
`WatchRemoteConfigOnChannel`是可以获取到最新值,但需要调用方判断是否有变更,
是否能提供一个配置变更的方法

**Comment by shima-park** [comment]
受限于作为viper扩展能提供的接口实现。
https://github.com/spf13/viper/blob/master/viper.go#L74

**Comment by eyotang** [comment]
刚需
