### ISSUE TITLE
agollo.Start()和viper同用时,配置变更后的读取操作会存在并发问题

### ISSUE THREAD

**Issue by 63isOK** [shima-park/agollo#75]
如果存在两个longPoll,在read时会读到旧值.

处理方式:
1. 在文档中添加说明,避免这种错误使用场景
2. 保证read的原子性

**Comment by shima-park** [comment]
你好，上面说的这两个有示例代码吗。
1.longPoll使用sync.Once启动，一个实例不会启动两个。是什么场景会同时存在两个longPoll。
2.从apollo获取数据成功后，内部配置的值修改使用sync.Map.Store做覆盖更新，有锁保护的。
