### ISSUE TITLE
签名计算bug

### ISSUE THREAD

**Issue by kinglf** [shima-park/agollo#78]
ConfigServerURL = http://apollo.meta/configsvc-dev 时, 使用token计算签名时,会把 pathwithquery部分的 /configsvc-dev 漏掉,导致签名失败, 建议在使用requestURI时,不要简单拼接,而是使用url.parse获取
![image](https://user-images.githubusercontent.com/19337680/186856270-fad55ac1-f7b3-4f5b-84c7-02445988958c.png)

**Comment by shima-park** [comment]
感谢反馈

**Comment by shima-park** [comment]
在v1.2.13版本中修复了这个问题。
https://github.com/shima-park/agollo/releases/tag/v1.2.13

**Comment by kinglf** [comment]
> 在v1.2.13版本中修复了这个问题。 https://github.com/shima-park/agollo/releases/tag/v1.2.13

双击666
